### ISSUE TITLE
Where is qms_dataset.ft

### ISSUE THREAD

**Issue by CS-FantaC** [Jill0001/QMS#1]
In qms_train.py funcion main line:237 ft_file = 'dataset/qms_dataset.ft' 
 I was wondering how can I get qms_dataset.ft? There is no file named qms_dataset.ft in directory dataset

**Comment by Jill0001** [comment]
There's a mistake in the Google Drive link. I've updated it. The qms_dataset.ft could be found in https://drive.google.com/file/d/1yVJTbIaRGEc0ypQOBP0B_4wfmT-c06rp/view?usp=drive_link
